@startuml Structure

title "DLA Program Structure"

together {
  package "Main Module" {
    [main_loop]
    [main]
  }
  
  package "Particle Module" {
    [init_particles]
    [random_wiggle]
  }
  
  package "Helpers Module" {
      [write_string]
      [random_num]
  }
}

package "UI Module" {
  [refresh_display]
  [render_particle]
}

' Main Connections
main --> init_particles : " initialize all\n particles"
main_loop --> random_wiggle : " update all\n particles"
main_loop --> refresh_display : "update display\n once per loop"

' Particle Connections
init_particles --> random_num : "set positions"
random_wiggle --> random_num : " update positions"

' UI Connections
refresh_display --> render_particle : "draw each\n particle on\n the screen"

' Helpers Connections

@enduml