@startuml Structure

title "DLA Program Structure"

package "Main Module" {
  [main_loop]
  [main]
}

package "Particle Module" {
  [init_particles]
  [random_wiggle]
  [check_touching]
  [is_stuck]
}

together {
  package "UI Module" {
    [refresh_display]
    [render_particle]
  }
  
  package "Helpers Module" {
      [random_num]
      [write_string]
  }
}

' Main Connections
main --> init_particles : "initialize\n particles"
main_loop --> random_wiggle : "update\n particles"
main_loop --> refresh_display : "update\n   display"

' Particle Connections
init_particles --> random_num
random_wiggle --> random_num : "position\n data"
random_wiggle --> check_touching : "check\n neighboring\n coord"

check_touching --> is_stuck : "search for\n stuck particles\n at coords"

' UI Connections
refresh_display --> render_particle : "add particle\n to screen\n buffer"
refresh_display --> write_string

' Helpers Connections
random_num -[Hidden]- write_string

@enduml